### ISSUE TITLE
Explore var spec configuration

### ISSUE THREAD

**Issue by raghu1121** [kengz/SLM-Lab#268]
I see few jsons with the below configurations for 
`explore_var_spec`
`"explore_var_spec": {
          "name": "linear_decay",
          "start_val": 3.0,
          "end_val": 1.0,
          "start_step": 0,
          "end_step": 2000,
        },`

I know that the below one is possible 

`"explore_var_spec": {
          "name": "linear_decay",
          "start_val": 1.0,
          "end_val": 0.1,
          "start_step": 0,
          "end_step": 2000,
        },`

Can ` "start_val": > 1` be possible? or i missed something !!

**Comment by kengz** [comment]
Hi @raghu1121 ,
the `explore_var_spec` goes with the `action_policy`.

If `"action_policy": "epsilon_greedy",`, then `explore_var` is epsilon, so its start value can be `1.0` (full exploration), and decay to `0.1` or `0.01` (less exploration). For this, since epsilon represents the probability of exploration (random action), `start_val > 1` is undefined.

If `"action_policy": "boltzmann",`, then `explore_var` is tau, which is a division factor, so its value is something bigger than 1.0, say 3 or 5 (more exploration), then decays to 1.0. For this, `start_val > 1` is ok.

**Comment by raghu1121** [comment]
Thanks Keng.
