### ISSUE TITLE
Resolve Package Not Found during setup

### ISSUE THREAD

**Issue by raymondchua** [kengz/SLM-Lab#75]
Hi, 
I ran the following command `bin/setup` and got the following error:

```
--- Installing brew ---
Brew is already installed
--- Installing brew system dependencies ---
--- Installing Atom and Hydrogen for interactive computing ---
Atom is already installed
Hydrogen is already installed
--- Installing NodeJS Lab interface ---
NodeJS is already installed
--- Installing npm modules for Lab interface ---
Npm modules are already installed
--- Installing Python for Lab backend ---
Python3 is already installed
--- Installing Conda ---
Conda is already installed
--- Installing Conda environment ---
conda env lab is already installed
--- Updating Conda environment ---
Fetching package metadata .............
Solving package specifications: 

ResolvePackageNotFound: 
  - pytorch 0.3.0*
  - mkl >=2018
  - torchvision 0.2.0*
  - pytorch >=0.3
  - mkl >=2018
```

At the moment, I overcome the issue by adding anaconda as a channel in the environment.yml 
Not sure if this is the most elegant approach.

**Comment by kengz** [comment]
Thanks for the report.

Likely due to improper linkage of anaconda as the default channel. Manually run `conda config --add channels anaconda` then rerun installation would achieve the same solution.

Added issue to the doc debugging page: https://kengz.gitbooks.io/slm-lab/content/installation/debugging.html
